services:
  - type: web
    name: wheelernc
    runtime: static
    plan: free
    repo: https://github.com/Parallax-Advisory/wheelernc
    branch: main
    buildCommand: ""
    staticPublishPath: .
    domains:
      - wheelernc.com
      - www.wheelernc.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
